---
system:
  url: http://192.168.188.100/:5000
  endpoint: /api/post
  rabbitmq_host: localhost
  rabbitmq_port: 5672
  rabbitmq_username: guest
  rabbitmq_password: guest
  rabbitmq_exchange: myexchange
  rabbitmq_routing_key: myqueue
  rabbitmq_vhost: /
  rabbitmq_queue_durable: true

api_pack:
  api_key: <your_api_key_here>

  sensors:
    get_data:
      host: "{{ system.rabbitmq_host }}"
      port: "{{ system.rabbitmq_port }}"
      username: "{{ system.rabbitmq_username }}"
      password: "{{ system.rabbitmq_password }}"
      exchange: "{{ system.rabbitmq_exchange }}"
      routing_key: "{{ system.rabbitmq_routing_key }}"
      vhost: "{{ system.rabbitmq_vhost }}"
      queue_durable: "{{ system.rabbitmq_queue_durable }}"

  actions:
    get_data:
      api_url: "{{ system.url }}"
      endpoint: "{{ system.endpoint }}"
      headers:
        Authorization: "Bearer {{ api_pack.api_key }}"
