apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-qed-sm
  labels:
    name: prometheus
    release: prometheus
spec:
  selector:
    matchLabels:
      qed_monitoring: prometheus
  namespaceSelector:
    any: true
  endpoints:
    - port: http
    - port: metrics
