# Three-node (two workers and one controller)
# To add more worker nodes, duplicate line 22
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: st2
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"    
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP
- role: worker
- role: worker