apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  {{- $name := print .Release.Name "-st2-auth" }}
  name: {{ $name }}
  {{- $labelsYaml := (include "stackstorm-ha.labels" (list $ "st2")) }}
  labels: {{- include "stackstorm-ha.labels" (list $ "st2") | nindent 4 }}
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    ST2_AUTH_USERNAME: {{ .Values.st2.username }}
    ST2_AUTH_PASSWORD: {{ .Values.st2.password }}
  template:
    metadata:
      annotations:
        description: StackStorm username and password, used for basic .htaccess auth
      name: {{ $name }}
      labels: {{ $labelsYaml | nindent 8 }}
    type: Opaque

