---
    name: configGen
    description: generating templates
    enabled: true
    runner_type: python-script
    entry_point: configGen.py

    parameters:
      input_vars:
        type: "object"
        description: "A dictionary of input variables and their values"
        default: {}
        required: false
      git_branch:
        type: "string"
        description: "The path to the clone directory"
        default: ""
        required: true
      config_template:
        type: "string"
        description: "The path to the Jinja2 config template"
        default: ""
        required: true
      config_file:
        type: "string"
        description: "The path to the output config file"
        default: ""
        required: true