{{- if .Values.st2.overrides }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-st2-overrides-configs
  annotations:
    description: StackStorm override configs defined in helm values, shipped in (or copied to) '/opt/stackstorm/overrides'
  labels:
    app: st2
    tier: backend
    vendor: stackstorm
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{ toYaml .Values.st2.overrides | indent 2 }}
{{- end }}
