---
    name: configGen
    description: generating templates
    enabled: true
    runner_type: local-shell-script
    entry_point: configGen.sh

    parameters:
      # repo_url:
      #   type: "string"
      #   description: "The URL of the Git repository"
      #   default: ""
      #   required: true
      # branch:
      #   type: "string"
      #   description: "The name of the branch to clone"
      #   default: ""
      #   required: true
      # clone_dir:
      #   type: "string"
      #   description: "The path to the clone directory"
      #   default: ""
      #   required: true
      config_template:
        type: "string"
        description: "The path to the Jinja2 config template"
        default: ""
        required: true
      config_file:
        type: "string"
        description: "The path to the output config file"
        default: ""
        required: true
      input_vars:
        type: "object"
        description: "A dictionary of input variables and their values"
        default: {}
        required: false