{{- if ( not (eq "" ($.Files.Get "data/st2.conf"))) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-base-config
  labels:
    app: st2
    tier: backend
    vendor: stackstorm
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  st2.conf: |
{{ $.Files.Get "data/st2.conf" | indent 4  }}
{{- end }}