name: Deliver webhook on push to main
on:
  push:
    branches:
      - main
jobs:

  azure:
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.CLIENT_ID }}","clientSecret":"${{ secrets.CLIENT_SECRET }}","subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}","tenantId":"${{ secrets.TENANT_ID }}"}'
      - name: Secret Sync
        uses: mbmcmullen27/azure-secrets@v1.0
        id: secrets
        with:
          keyvault: argocd-tfs-kvault
          token: ${{ secrets.GH_PAT }}
          pattern: 'st2-api-key-dev$'
        output:
          secret-count: ${{ steps.secrets.outputs }}
      - name: Add Secret to Env Variable
        run: echo "SECRET_COUNT=${{ steps.secrets.outputs }}" >> $GITHUB_ENV



#      - name: Send webhook request
#        run: |
#          curl -X POST http://st2.dev.tiacloud.io/api/v1/webhooks/argocd_trigger \
#          -H "Content-Type: application/json" \
#          -H "St2-Api-Key: NmU0MjYxNDYzNGY3NTM0YTJkY2U2ZDJlYmUxYmRkOWUwMDMzZDlkNTRhZTcwYTMwYzhlMTgxMzJiYjY5MzJkNg" \
#          -d \
#          '{
#                "git_branch": "argocd-jinja2-crossplane-tf-demo",
#                "config_template": "config.j2",
#                "config_file": "config.yml",
#                "yaml_template": "namespace_config.j2",
#                "yaml_file": "namespaces.yaml",
#                "input_vars": {
#                  "teamName": "fork",
#                  "server": "test3",
#                  "environment": "dev-dev",
#                  "token": "hello",
#                  "ca": "yea"
#            }
#          }'
