name: Deliver webhook on push to main
on:
  push:
    branches:
      - main
jobs:
  Git-Sync-Feature-to-StackStorm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.CLIENT_ID }}","clientSecret":"${{ secrets.CLIENT_SECRET }}","subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}","tenantId":"${{ secrets.TENANT_ID }}"}'
      - name: Azure CLI
        uses: azure/CLI@v1
        id: GetSecretValueWithCLI
        with:
          inlineScript: |
            az keyvault secret show --name "st2-api-key-dev" --vault-name "argocd-tfs-kvault" --query "value"
      - name: Send webhook request to StacKStorm
        run: |
          curl -X POST http://st2.dev.tiacloud.io/api/v1/webhooks/argocd_trigger \
          -H "Content-Type: application/json" \
          -H "St2-Api-Key: ${{ env.st2-api-key-dev }}" \
          -d \
          '{
                "git_branch": "argocd-jinja2-crossplane-tf-demo",
                "config_template": "config.j2",
                "config_file": "config.yml",
                "yaml_template": "namespace_config.j2",
                "yaml_file": "namespaces.yaml",
                "input_vars": {
                  "teamName": "fork",
                  "server": "test3",
                  "environment": "dev-dev",
                  "token": "hello",
                  "ca": "yea"
            }
          }'
          
          

